<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class BarangayTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            DB::table('barangays')->delete();
            $barangay = array(
                array('id' => 1,'city_id'=>'1','name' => "Alubijid"),
                array('id' => 2,'city_id'=>'1','name' => "Guinabsan"),
                array('id' => 3,'city_id'=>'1','name' => "Lower Olave"),
                array('id' => 4,'city_id'=>'1','name' => "Macalang"),
                array('id' => 5,'city_id'=>'1','name' => "Malpoc"),
                array('id' => 6,'city_id'=>'1','name' => "Manapa"),
                array('id' => 7,'city_id'=>'1','name' => "Matabao"),
                array('id' => 8,'city_id'=>'1','name' => "Poblacion 1"),
                array('id' => 9,'city_id'=>'1','name' => "Poblacion 2"),
                array('id' => 10,'city_id'=>'1','name' => "Poblacion 3"),
                array('id' => 11,'city_id'=>'1','name' => "Poblacion 4"),
                array('id' => 12,'city_id'=>'1','name' => "Poblacion 5"),
                array('id' => 13,'city_id'=>'1','name' => "Poblacion 6"),
                array('id' => 14,'city_id'=>'1','name' => "Poblacion 7"),
                array('id' => 15,'city_id'=>'1','name' => "Poblacion 8"),
                array('id' => 16,'city_id'=>'1','name' => "Poblacion 9"),
                array('id' => 17,'city_id'=>'1','name' => "Poblacion 10"),
                array('id' => 18,'city_id'=>'1','name' => "Rizal"),
                array('id' => 19,'city_id'=>'1','name' => "Sacol"),
                array('id' => 20,'city_id'=>'1','name' => "Simbalan"),
                array('id' => 21,'city_id'=>'1','name' => "Talo-ao"),
                array('id' => 22,'city_id'=>'2','name' => "Agao Pob. (Brgy. 3)"),
                array('id' => 23,'city_id'=>'2','name' => "Agusan Pequeno"),
                array('id' => 24,'city_id'=>'2','name' => "Ambago"),
                array('id' => 25,'city_id'=>'2','name' => "Amparo"),
                array('id' => 26,'city_id'=>'2','name' => "Ampayon"),
                array('id' => 27,'city_id'=>'2','name' => "Anticala"),
                array('id' => 28,'city_id'=>'2','name' => "Antongalon"),
                array('id' => 29,'city_id'=>'2','name' => "Aupagan"),
                array('id' => 30,'city_id'=>'2','name' => "Baan Km. 3"),
                array('id' => 31,'city_id'=>'2','name' => "Baan Riverside"),
                array('id' => 32,'city_id'=>'2','name' => "Babag"),
                array('id' => 33,'city_id'=>'2','name' => "Bading"),
                array('id' => 34,'city_id'=>'2','name' => "Bancasi"),
                array('id' => 35,'city_id'=>'2','name' => "Banza"),
                array('id' => 36,'city_id'=>'2','name' => "Baobaoan"),
                array('id' => 37,'city_id'=>'2','name' => "Basag"),
                array('id' => 38,'city_id'=>'2','name' => "Bayanihan Pob(Brgy.27)"),
                array('id' => 39,'city_id'=>'2','name' => "Bilay"),
                array('id' => 40,'city_id'=>'2','name' => "Bit-os"),
                array('id' => 41,'city_id'=>'2','name' => "Bitan-agan"),
                array('id' => 42,'city_id'=>'2','name' => "Bobon"),
                array('id' => 43,'city_id'=>'2','name' => "Bonbon"),
                array('id' => 44,'city_id'=>'2','name' => "Bugabos"),
                array('id' => 45,'city_id'=>'2','name' => "Bugsukan"),
                array('id' => 46,'city_id'=>'2','name' => "Buhangin Pob(Brgy.19)"),
                array('id' => 47,'city_id'=>'2','name' => "Cabcabon"),
                array('id' => 48,'city_id'=>'2','name' => "Camayahan"),
                array('id' => 49,'city_id'=>'2','name' => "Dagohoy"),
                array('id' => 50,'city_id'=>'2','name' => "Dankias"),
                array('id' => 51,'city_id'=>'2','name' => "De Oro"),
                array('id' => 52,'city_id'=>'2','name' => "Diego Silang"),
                array('id' => 53,'city_id'=>'2','name' => "Don Francisco"),
                array('id' => 54,'city_id'=>'2','name' => "Doongan"),
                array('id' => 55,'city_id'=>'2','name' => "Dulag"),
                array('id' => 56,'city_id'=>'2','name' => "Dumalagan"),
                array('id' => 57,'city_id'=>'2','name' => "Florida"),
                array('id' => 58,'city_id'=>'2','name' => "Golden Ribbon"),
                array('id' => 59,'city_id'=>'2','name' => "Holy Redeemer"),
                array('id' => 60,'city_id'=>'2','name' => "Humabon Pob."),
                array('id' => 61,'city_id'=>'2','name' => "Imadejas Pob."),
                array('id' => 62,'city_id'=>'2','name' => "Jose Rizal Pob."),
                array('id' => 63,'city_id'=>'2','name' => "Kinamlutan"),
                array('id' => 64,'city_id'=>'2','name' => "Lapu-Lapu Pob."),
                array('id' => 65,'city_id'=>'2','name' => "Lemon"),
                array('id' => 66,'city_id'=>'2','name' => "Leon Kilat"),
                array('id' => 67,'city_id'=>'2','name' => "Libertad"),
                array('id' => 68,'city_id'=>'2','name' => "Limaha"),
                array('id' => 69,'city_id'=>'2','name' => "Los Angeles"),
                array('id' => 70,'city_id'=>'2','name' => "Lumbocan"),
                array('id' => 71,'city_id'=>'2','name' => "Maguinda"),
                array('id' => 72,'city_id'=>'2','name' => "Mahay"),
                array('id' => 73,'city_id'=>'2','name' => "Mahogany Pob"),
                array('id' => 74,'city_id'=>'2','name' => "Maibu"),
                array('id' => 75,'city_id'=>'2','name' => "Mandamo"),
                array('id' => 76,'city_id'=>'2','name' => "Manila De Bugabos"),
                array('id' => 77,'city_id'=>'2','name' => "Maon Pob"),
                array('id' => 78,'city_id'=>'2','name' => "Masao"),
                array('id' => 79,'city_id'=>'2','name' => "Maug"),
                array('id' => 80,'city_id'=>'2','name' => "New Society Village"),
                array('id' => 81,'city_id'=>'2','name' => "Nong-Nong"),
                array('id' => 82,'city_id'=>'2','name' => "Obrero Pob."),
                array('id' => 83,'city_id'=>'2','name' => "Ong Yiu Pob."),
                array('id' => 84,'city_id'=>'2','name' => "Pagatpatan"),
                array('id' => 85,'city_id'=>'2','name' => "Pangabugan"),
                array('id' => 86,'city_id'=>'2','name' => "Pianing"),
                array('id' => 87,'city_id'=>'2','name' => "Pigdaulan"),
                array('id' => 88,'city_id'=>'2','name' => "Pinamanculan"),
                array('id' => 89,'city_id'=>'2','name' => "Port Poyohon"),
                array('id' => 90,'city_id'=>'2','name' => "Rajah Soliman"),
                array('id' => 91,'city_id'=>'2','name' => "Salvacion"),
                array('id' => 92,'city_id'=>'2','name' => "San Ignacio"),
                array('id' => 93,'city_id'=>'2','name' => "San Mateo"),
                array('id' => 94,'city_id'=>'2','name' => "San Vicente"),
                array('id' => 95,'city_id'=>'2','name' => "Santo Nino"),
                array('id' => 96,'city_id'=>'2','name' => "Sikatuna Pob"),
                array('id' => 97,'city_id'=>'2','name' => "Silongan Pob"),
                array('id' => 98,'city_id'=>'2','name' => "Sumile"),
                array('id' => 99,'city_id'=>'2','name' => "Sumilihon"),
                array('id' => 100,'city_id'=>'2','name' => "Tagabaca"),
                array('id' => 101,'city_id'=>'2','name' => "Taguibo"),
                array('id' => 102,'city_id'=>'2','name' => "Taligaman"),
                array('id' => 103,'city_id'=>'2','name' => "Tandang Sora"),
                array('id' => 104,'city_id'=>'2','name' => "Tiniwisan"),
                array('id' => 105,'city_id'=>'2','name' => "Tungao"),
                array('id' => 106,'city_id'=>'2','name' => "Urduja Pob."),
                array('id' => 107,'city_id'=>'2','name' => "Villa Kananga"),
                );
                DB::table('barangays')->insert($barangay);
            
    }
}
